spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/mindata}
    username: ${DB_USER:usuario}
    password: ${DB_PASS:contraseña}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    baseline-on-migrate: true

  kafka:
    bootstrap-servers:  ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    consumer:
      group-id:  ${KAFKA_CONSUMER_GROUP:my-consumer-group}
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  cache:
    type: redis

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  main:
    allow-circular-references: true